cure_flora: &cure_flora
  girl_name:    cure_flora
  human_name:   春野はるか
  precure_name: キュアフローラ
  cast_name:    嶋村侑
  color:        pink
  created_date: 2015-02-01 # episode 1
  birthday:     4/10
  transform_message: |-
    プリキュア！プリンセスエンゲージ！
    咲き誇る花のプリンセス！キュアフローラ！
    強く、やさしく、美しく！
    Go!プリンセスプリキュア！
    冷たい檻に閉ざされた夢、返していただきますわ！
    お覚悟はよろしくて？
  extra_names:
  attack_messages:
    - |-
      エクスチェンジ！モードエレガント！
      舞え、花よ！プリキュア・フローラル・トルビヨン！
      (ドリーミング)
      ごきげんよう
  transform_calls:
    - princess_engage
cure_mermaid: &cure_mermaid
  girl_name:    cure_mermaid
  human_name:   海藤みなみ
  precure_name: キュアマーメイド
  cast_name:    浅野真澄
  color:        blue
  created_date: 2015-02-08 # episode 2
  birthday:     7/20
  transform_message: |-
    プリキュア！プリンセスエンゲージ！
    澄み渡る海のプリンセス！キュアマーメイド！
    強く、やさしく、美しく！
    Go!プリンセスプリキュア！
    冷たい檻に閉ざされた夢、返していただきますわ！
    お覚悟はよろしくて？
  extra_names:
  attack_messages:
    - |-
      エクスチェンジ！モードエレガント！
      高鳴れ、海よ！プリキュア・マーメイド・リップル！
      (ドリーミング)
      ごきげんよう
  transform_calls:
    - princess_engage
cure_twinkle: &cure_twinkle
  girl_name:    cure_twinkle
  human_name:   天ノ川きらら
  precure_name: キュアトゥインクル
  cast_name:    山村響
  color:        yellow
  created_date: 2015-02-22 # episode 4
  birthday:     9/12
  transform_message: |-
    プリキュア！プリンセスエンゲージ！
    きらめく星のプリンセス！キュアトゥインクル！
    強く、やさしく、美しく！
    Go!プリンセスプリキュア！
    冷たい檻に閉ざされた夢、返していただきますわ！
    お覚悟はよろしくて？
  extra_names:
  attack_messages:
    - |-
      エクスチェンジ！モードエレガント！
      キラキラ、星よ！プリキュア・トゥインクル・ハミング！
      (ドリーミング)
      ごきげんよう
  transform_calls:
    - princess_engage
cure_scarlet: &cure_scarlet
  girl_name:       cure_scarlet
  human_name:      紅城トワ
  human_full_name: プリンセス・ホープ・ディライト・トワ
  precure_name:    キュアスカーレット
  cast_name:       沢城みゆき
  color:           red
  created_date:    2015-07-05 # episode 22
  birthday:        12/15
  transform_message: |-
    プリキュア！プリンセスエンゲージ！
    深紅の炎のプリンセス！キュアスカーレット！
    強く、やさしく、美しく！
    Go!プリンセスプリキュア！
    冷たい檻に閉ざされた夢、返していただきますわ！
    お覚悟決めなさい！
  extra_names:
  attack_messages:
    - |-
      エクスチェンジ！モードエレガント！
      羽ばたけ炎の翼！プリキュア・フェニックス・ブレイズ！
      (ドリーミング)
      ごきげんよう
  transform_calls:
    - princess_engage
flora:
  <<: *cure_flora
mermaid:
  <<: *cure_mermaid
twinkle:
  <<: *cure_twinkle
scarlet:
  <<: *cure_scarlet
