cure_yell: &cure_yell
  girl_name:    cure_yell
  human_name:   野乃はな
  precure_name: キュアエール
  cast_name:    引坂理絵
  color:        pink
  created_date: 2018-02-04 # episode 1
  birthday: 1/20
  transform_message: |-
    ミライクリスタル！
    ハートキラっと！
    は～ぎゅ～～！
    ぎゅ～！
    ぎゅ～～！
    輝く未来を抱きしめて！
    みんなを応援！元気のプリキュア！キュアエール！
  # extra_names:
  attack_messages:
    - |-
      フレフレ！ハート・フォー・ユー！
  transform_calls:
    - heart_kiratto
yell:
  <<: *cure_yell

cure_ange: &cure_ange
  girl_name:    cure_ange
  human_name:   薬師寺さあや
  precure_name: キュアアンジュ
  cast_name:    本泉莉奈
  color:        blue
  created_date: 2018-02-11 # episode 2
  birthday: 6/10
  transform_message: |-
    ミライクリスタル！
    ハートキラっと！
    は～ぎゅ～～！
    ぎゅ～！
    ぎゅ～～！
    輝く未来を抱きしめて！
    みんなを癒す！知恵のプリキュア！キュアアンジュ！
  # extra_names:
  attack_messages:
    - |-
      フレフレ！ハート・フェーザー！
  transform_calls:
    - heart_kiratto
ange:
  <<: *cure_ange

cure_etoile: &cure_etoile
  girl_name:    cure_etoile
  human_name:   輝木ほまれ
  precure_name: キュアエトワール
  cast_name:    小倉唯
  color:        yellow
  created_date: 2018-03-04 # episode 5
  birthday: 4/8
  transform_message: |-
    ミライクリスタル！
    ハートキラっと！
    は～ぎゅ～～！
    ぎゅ～！
    ぎゅ～～！
    輝く未来を抱きしめて！
    みんな輝け！力のプリキュア！キュアエトワール！
  # extra_names:
  attack_messages:
    - |-
      フレフレ！ハート・スター！
  transform_calls:
    - heart_kiratto
etoile:
  <<: *cure_etoile

cure_macherie: &cure_macherie
  girl_name:    cure_macherie
  human_name:   愛崎えみる
  precure_name: キュアマシェリ
  cast_name:    田村奈央
  color:        red
  created_date: 2018-06-17 # episode 20
  birthday: 7/15
  transform_message: |-
    ミライクリスタル！
    ハートキラっと！
    は～ぎゅ～～！
    ぎゅ～！
    ぎゅ～～！
    輝く未来を抱きしめて！
    みんな大好き！愛のプリキュア！キュアマシェリ！
  # extra_names:
  attack_messages:
    - |-
      Are you ready?
      フレフレ！ハート・ソング！
  transform_calls:
    - heart_kiratto
macherie:
  <<: *cure_macherie

cure_amour: &cure_amour
  girl_name:    cure_amour
  human_name:   ルールー・アムール
  precure_name: キュアアムール
  cast_name:    田村ゆかり
  color:        purple
  created_date: 2018-06-17 # episode 20
  birthday: 9/23
  transform_message: |-
    ミライクリスタル！
    ハートキラっと！
    は～ぎゅ～～！
    ぎゅ～！
    ぎゅ～～！
    輝く未来を抱きしめて！
    みんな大好き！愛のプリキュア！キュアアムール！
  # extra_names:
  attack_messages:
    - |-
      いきます！
      フレフレ！ハート・ダンス！
  transform_calls:
    - heart_kiratto
amour:
  <<: *cure_amour
