#######################################################
dx1: &dx1
  title: 映画 プリキュアオールスターズDX みんなともだちっ☆奇跡の全員大集合!
  started_date: 2009-03-20
dx:
  <<: *dx1
#######################################################
dx2: &dx2
  title: 映画 プリキュアオールスターズDX2 希望の光☆レインボージュエルを守れ!
  started_date: 2010-03-20
#######################################################
dx3: &dx3
  title: 映画 プリキュアオールスターズDX3 未来にとどけ! 世界をつなぐ☆虹色の花
  started_date: 2011-03-19
#######################################################
ns1: &ns1
  title: 映画 プリキュアオールスターズNewStage みらいのともだち
  started_date: 2012-03-17
  extra_girls:
    - cure_echo
ns:
  <<: *ns1
new_stage:
  <<: *ns1
new_stage1:
  <<: *ns1
#######################################################
ns2: &ns2
  title: 映画 プリキュアオールスターズNewStage2 こころのともだち
  started_date: 2013-03-16
new_stage2:
  <<: *ns2
#######################################################
ns3: &ns3
  title: 映画 プリキュアオールスターズ NewStage3 永遠のともだち
  started_date: 2014-03-15
  extra_girls:
  - cure_echo
new_stage3:
  <<: *ns3
#######################################################
sc: &sc
  title: 映画 プリキュアオールスターズ 春のカーニバル
  started_date: 2015-03-14
spring_carnival:
  <<: *sc
#######################################################
stmm: &stmm
  title: 映画 プリキュアオールスターズ みんなで歌う 奇跡の魔法！
  started_date: 2016-03-19
  extra_girls:
  - cure_echo
sing_together_miracle_magic:
  <<: *stmm
#######################################################
dream_stars: &dream_stars
  title: 映画プリキュアドリームスターズ！
  started_date: 2017-03-18
dc:
  <<: *dream_stars
#######################################################
super_stars: &super_stars
  title: 映画プリキュアスーパースターズ！
  started_date: 2018-03-17
ss:
  <<: *super_stars
#######################################################
memories: &memories
  title: 映画ＨＵＧっと！プリキュア♡ふたりはプリキュア オールスターズメモリーズ
  started_date: 2018-10-27
#######################################################
miracle_universe: &miracle_universe
  title: 映画プリキュアミラクルユニバース
  started_date: 2019-03-16
